{
 "title": "Milvus Standalone",
 "description": "Visualize Milvus Standalone metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Data Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flush Request Rate",
   "type": "timeseries",
   "description": "The number of times each data node receives a buffer flush request per second within the past two minute.\n\nThe accumulated number of times a data node receives a flush request from a data coord.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_flush_req_count{}[2m])/120) by (status, node_id)"
    }
   ]
  },
  {
   "title": "Flush Operate Rate",
   "type": "timeseries",
   "description": "The number of times each data node flushes a buffer per second within the past two minutes.\n\nThe accumulated number of times a data node flushes a buffer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(milvus_datanode_flush_buffer_op_count{}[2m])/120) by (status, node_id)"
    }
   ]
  },
  {
   "title": "Producer Num",
   "type": "timeseries",
   "description": "The number of producers created on each data node.\n\nThe number of consumers created on each data node.\n\nEach shard in a collection corresponds to a delta channel producer and a timetick channel producer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(milvus_datanode_producer_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Consumer Num",
   "type": "timeseries",
   "description": "The number of consumers created on each data node.\n\nThe number of consumers created on each data node.\n\nEach flowgraph corresponds to a consumer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(milvus_datanode_consumer_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Flowgraph Num",
   "type": "timeseries",
   "description": "The number of flowgraph objects that correspond to each data node.\n\nThe number of flowgraph objects.\n\nEach shard in a collection corresponds to a flowgraph object.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(milvus_datanode_flowgraph_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "description": "The average, maximum, and minimum number of epoch time synced by each data node in all physical topics.\n\nThe epoch time (Unix time, the milliseconds passed ever since January 1, 1970.) of each physical topic on a data node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg(milvus_datanode_sync_epoch_time{}) by (node_id) "
    },
    {
     "expr": "max(milvus_datanode_sync_epoch_time{}) by (node_id) "
    },
    {
     "expr": "min(milvus_datanode_sync_epoch_time{}) by (node_id)"
    }
   ]
  },
  { "title": "Data Coord", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Stored Rows Rate",
   "type": "timeseries",
   "description": "The average number of rows flushed per second within the past two minutes.\n\nThe accumulated number of rows flushed by data coord.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(milvus_datacoord_stored_rows_count{}[2m])/120) by ( node_id)"
    }
   ]
  },
  {
   "title": "Data Node Num",
   "type": "timeseries",
   "description": "The number of data nodes managed by data coord.\n\nThe number of data nodes managed by data coord.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(milvus_datacoord_datanode_num{})"
    }
   ]
  },
  {
   "title": "Stored Rows",
   "type": "timeseries",
   "description": "The accumulated number of rows of valid and flushed data in data coord.\n\nThe accumulated number of rows of valid and flushed data in data coord.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(milvus_datacoord_stored_rows_num{})"
    }
   ]
  },
  {
   "title": "Segment Num",
   "type": "timeseries",
   "description": "The number of all types of segments recorded in metadata by data coord.\n\nThe number of all types of segments recorded in metadata by data coord.\n\nTypes of segment include: dropped, flushed, flushing, growing, and sealed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(milvus_datacoord_segment_num{}) by (segment_state)"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "description": "The average, maximum, and minimum number of epoch time synced by data coord in each physical channel.\n\nEach physical channel's epoch time (Unix time, the milliseconds passed ever since January 1, 1970).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "avg(milvus_datacoord_sync_epoch_time{})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(milvus_datacoord_sync_epoch_time{})",
     "legendFormat": "max"
    },
    {
     "expr": "min(milvus_datacoord_sync_epoch_time{})",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "Query Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Ready Read Task Length",
   "type": "timeseries",
   "description": "The length of the queue of read requests to be executed in each query node.\n\nThe length of the queue of read requests to be executed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_ready_len{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Unsolved Read Task Length",
   "type": "timeseries",
   "description": "The length of the queue of unsolved read requests in each query node.\n\nThe length of the queue of unsolved read requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_unsolved_len{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Parallel Read Task Num",
   "type": "timeseries",
   "description": "The number of concurrent read requests currently executed in each query node.\n\nThe number of concurrent read requests currently executed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_read_task_concurrency{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Flowgraph Num",
   "type": "timeseries",
   "description": "The number of flowgraphs in each query node.\n\nThe number of flowgraphs in each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_flowgraph_num{}) by (node_id)"
    }
   ]
  },
  {
   "title": "Load Segment Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the time each query node takes to load a segment in the past two minutes.\n\nThe time each query node takes to load a segment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, node_id) (rate(milvus_querynode_load_segment_latency_bucket{}[2m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(increase(milvus_querynode_load_segment_latency_sum{}[2m])) by( node_id) / sum(increase(milvus_querynode_load_segment_latency_count{}[2m])) by( node_id)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Consumer Num",
   "type": "timeseries",
   "description": "The number of consumers in each query node.\n\nThe number of consumers in each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_consumer_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Delta Virtual Channel",
   "type": "timeseries",
   "description": "The number of delta channels watched by each query node.\n\nThe number of delta channels watched by each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_delta_vchannel_num{}) by (node_id)"
    }
   ]
  },
  {
   "title": "DML Virtual Channel",
   "type": "timeseries",
   "description": "The number of DML virtual channels watched by each query node.\n\nThe number of DML virtual channels watched by each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_dml_vchannel_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Queryable Entity Num",
   "type": "timeseries",
   "description": "The number of queryable and searchable entities on each query node.\n\nThe number of queryable and searchable entities on each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_entity_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Segment Loaded Num",
   "type": "timeseries",
   "description": "The number of segments loaded into memory by each query node.\n\nThe number of segments loaded by each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_segment_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Partition Loaded Num",
   "type": "timeseries",
   "description": "The number of partitions loaded into memory by each query node.\n\nThe number of partitions loaded by each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_partition_num{}) by ( node_id)"
    }
   ]
  },
  {
   "title": "Collection Loaded Num",
   "type": "timeseries",
   "description": "The number of collections loaded into memory by each query node.\n\nThe number of collection loaded by each query node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum(milvus_querynode_collection_num{}) by ( node_id)"
    }
   ]
  },
  { "title": "Query Coord", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Query Node Num",
   "type": "timeseries",
   "description": "The number of query nodes managed by query coord.\n\nThe number of query nodes managed by query coord.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(milvus_querycoord_querynode_num{})"
    }
   ]
  },
  {
   "title": "Collection Loaded Num",
   "type": "timeseries",
   "description": "The number of collections that are currently loaded into memory.\n\nThe number of collections that are currently loaded by Milvus.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "sum(milvus_querycoord_collection_num{})"
    }
   ]
  },
  {
   "title": "Parent Load Task",
   "type": "timeseries",
   "description": "The number of parent load tasks.\n\nThe number of sub load tasks.\n\nEach load request corresponds to a parent task in the task queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum(milvus_querycoord_parent_task_num{})"
    }
   ]
  },
  {
   "title": "Sub-Load Task",
   "type": "timeseries",
   "description": "The number of sub load tasks.\n\nA query coord splits a load request into multiple sub load tasks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "sum(milvus_querycoord_child_task_num{})"
    }
   ]
  },
  {
   "title": "Load Request Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of load request latency within the past two minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_load_latency_bucket{}[2m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(increase(milvus_querycoord_load_latency_sum{}[2m])) / sum(increase(milvus_querycoord_load_latency_count{}[2m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Sub-Load Task Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the latency of a sub load task within the past two minutes.\n\nThe latency to complete a sub load task.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_querycoord_child_task_latency_bucket{}[2m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(increase(milvus_querycoord_child_task_latency_sum{}[2m])) / sum(increase(milvus_querycoord_child_task_latency_count{}[2m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Load Request Rate",
   "type": "timeseries",
   "description": "The number of load requests per second within the past two minutes.\n\nThe accumulated number of load requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "sum(increase(milvus_querycoord_load_req_count{}[2m])/120) by (status)"
    }
   ]
  },
  { "title": "Root Coord", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "Credential Num",
   "type": "timeseries",
   "description": "The total number of credentials.\n\nThe total number of credentials in Milvus currently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_credential_num{})"
    }
   ]
  },
  {
   "title": "Msgstream Num",
   "type": "timeseries",
   "description": "The total number of msgstreams.\n\nThe total number of msgstreams in Milvus currently.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_msgstream_obj_num{})"
    }
   ]
  },
  {
   "title": "DML Channel Num",
   "type": "timeseries",
   "description": "The total number of DML channels.\n\nThe total number of DML channels existing in Milvus currently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_dml_channel_num{})"
    }
   ]
  },
  {
   "title": "Partition Num",
   "type": "timeseries",
   "description": "The total number of partitions.\n\nThe total number of partitions existing in Milvus currently.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_partition_num{})"
    }
   ]
  },
  {
   "title": "Collection Num",
   "type": "timeseries",
   "description": "The total number of collections.\n\nThe total number of collections existing in Milvus currently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_collection_num{})"
    }
   ]
  },
  {
   "title": "Timestamp Saved",
   "type": "timeseries",
   "description": "The pre-assigned timestamps that root coord saves in meta storage.\n\nThe pre-assigned timestamps that root coord saves in meta storage.\n\nThe timestamps are assigned 3 seconds earlier. And the timestamp is updated and saved in meta storage every 50 millisecond.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "expr": "milvus_rootcoord_timestamp_saved{}"
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "timeseries",
   "description": "The latest timestamp of root coord.\n\nThe latest timestamp of root coord.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "targets": [
    { "expr": "milvus_rootcoord_timestamp{}" }
   ]
  },
  {
   "title": "ID Alloc Rate",
   "type": "timeseries",
   "description": "The number of IDs assigned by root coord per second within the past two minutes.\n\nThe accumulated number of IDs assigned by root coord.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "targets": [
    {
     "expr": "sum(increase(milvus_rootcoord_id_alloc_count{}[2m])/120)"
    }
   ]
  },
  {
   "title": "Sync Timetick Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the time used by root coord to sync all timestamp to PChannel within the past two minutes.\n\nthe time used by root coord to sync all timestamp to pchannel.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(milvus_rootcoord_sync_timetick_latency_bucket{}[2m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "DDL Request Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of DDL request latency within the past two minutes.\n\nThe latency of all types of DDL requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, function_name) (rate(milvus_rootcoord_ddl_req_latency_bucket{}[2m])))",
     "legendFormat": "{p99  function_name=\"{{function_name}}\"}"
    },
    {
     "expr": "sum(increase(milvus_rootcoord_ddl_req_latency_sum{}[2m])) by (function_name) / sum(increase(milvus_rootcoord_ddl_req_latency_count{}[2m])) by (function_name)",
     "legendFormat": "{avg  function_name=\"{{function_name}}\"}"
    }
   ]
  },
  {
   "title": "DDL Request Rate",
   "type": "timeseries",
   "description": "The status and number of DDL requests per second within the past two minutes.\n\nThe total number of DDL requests including CreateCollection, DescribeCollection, DescribeSegments, HasCollection, ShowCollections, ShowPartitions, and ShowSegments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
   "targets": [
    {
     "expr": "sum(increase(milvus_rootcoord_ddl_req_count{}[2m])/120) by (status, function_name)"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "description": "The average, maximum, and minimum number of epoch time synced by each root coord in each physical channel (PChannel).\n\nEach physical channel's epoch time (Unix time, the milliseconds passed ever since January 1, 1970).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "avg(milvus_rootcoord_sync_epoch_time{})",
     "legendFormat": "avg"
    },
    {
     "expr": "max(milvus_rootcoord_sync_epoch_time{}) ",
     "legendFormat": "max"
    },
    {
     "expr": "min(milvus_rootcoord_sync_epoch_time{})",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 181 } },
  {
   "title": "Proxy Node Num",
   "type": "timeseries",
   "description": "The number of proxies created.\n\nThe number of proxies.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "targets": [
    {
     "expr": "sum(milvus_rootcoord_proxy_num{})"
    }
   ]
  },
  {
   "title": "DDL Request Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the latency of successfully receiving DDL requests by each proxy in the past two minutes.\n\nThe latency of successful DDL requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, function_name, node_id) (rate(milvus_proxy_ddl_req_latency_bucket{}[2m])))",
     "legendFormat": "{p99  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    },
    {
     "expr": "sum(increase(milvus_proxy_ddl_req_latency_sum{}[2m])) by (function_name, node_id) / sum(increase(milvus_proxy_ddl_req_latency_count{}[2m])) by (function_name, node_id)",
     "legendFormat": "{avg  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    }
   ]
  },
  {
   "title": "DML Request Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the latency of successfully receiving DML requests by each proxy in the past two minutes.\n\nThe latency of successful DQL requests excluding Insert and Delete requests.\n\nFor metrics of Insert and Delete requests, refer to milvus_proxy_mutation_latency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, function_name, node_id) (rate(milvus_proxy_dml_req_latency_bucket{}[2m])))",
     "legendFormat": "{p99  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    },
    {
     "expr": "sum(increase(milvus_proxy_dml_req_latency_sum{}[2m])) by (function_name, node_id) / sum(increase(milvus_proxy_dml_req_latency_count{}[2m])) by (function_name, node_id)",
     "legendFormat": "{avg  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    }
   ]
  },
  {
   "title": "DQL Request Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of the latency of successfully receiving DQL requests by each proxy in the past two minutes.\n\nThe latency of successful DQL requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, function_name, node_id) (rate(milvus_proxy_dql_req_latency_bucket{}[2m])))",
     "legendFormat": "{p99  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    },
    {
     "expr": "sum(increase(milvus_proxy_dql_req_latency_sum{}[2m])) by (function_name, node_id) / sum(increase(milvus_proxy_dql_req_latency_count{}[2m])) by (function_name, node_id)",
     "legendFormat": "{avg  function_name=\"{{function_name}}\", node_id=\"{{node_id}}\"}"
    }
   ]
  },
  {
   "title": "DDL Request Rate",
   "type": "timeseries",
   "description": "The status and number of DDL requests received per second by each proxy within the past two minutes.\n\nDML requests include CreateCollection, DropCollection, ShowCollection, CreatePartition, Flush, etc. This panel specifically shows the total number and the number of successful DDL requests.\n\nThe number of all types of DDL requests.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_ddl_req_count{}[2m])/120) by(function_name, status, node_id)"
    }
   ]
  },
  {
   "title": "DML Request Rate",
   "type": "timeseries",
   "description": "The status and number of DML requests received per second by each proxy within the past two minutes.\n\nDML requests include Insert, Delete, LoadCollection, HasCollection, ReleaseCollection, etc. This panel specifically shows the total number and the number of successful DML requests.\n\nThe number of all types of DML requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_dml_req_count{}[2m])/120) by(function_name, status, node_id)"
    }
   ]
  },
  {
   "title": "DQL Request Rate",
   "type": "timeseries",
   "description": "The status and number of DQL requests received per second by each proxy within the past two minutes.\n\nDQL requests include DescribeCollection, DescribeIndex, GetCollectionStatistics, HasCollection, Search, Query, ShowPartitions, etc. This panel specifically shows the total number and the number of successful DQL requests.\n\nThe number of all types of DQL requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_dql_req_count{}[2m])/120) by(function_name, status, node_id)"
    }
   ]
  },
  {
   "title": "Apply Timestamp Latency",
   "type": "timeseries",
   "description": "The average latency and the 99th percentile of timestamp application latency by each proxy within the past two minutes.\nThe latency of applying timestamp.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, node_id) (rate(milvus_proxy_apply_timestamp_latency_bucket{}[2m])))",
     "legendFormat": "p99_node[{{node_id}}]"
    },
    {
     "expr": "sum(increase(milvus_proxy_apply_timestamp_latency_sum{}[2m])) by (pod, node_id) / sum(increase(milvus_proxy_apply_timestamp_latency_count{}[2m])) by ( node_id)",
     "legendFormat": "avg_node[{{node_id}}]"
    }
   ]
  },
  {
   "title": "Cache Update Latency",
   "type": "timeseries",
   "description": "The latency of updating cache each time.\nThe average latency and the 99th percentile of cache update latency by proxy within the past two minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, node_id) (rate(milvus_proxy_cache_update_latency_bucket{}[2m])))",
     "legendFormat": "pct99_node[{{node_id}}]"
    },
    {
     "expr": "sum(increase(milvus_proxy_cache_update_latency_sum{}[2m])) by (node_id) / sum(increase(milvus_proxy_cache_update_latency_count{}[2m])) by (node_id)",
     "legendFormat": "avg_node[{{node_id}}]"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "The average cache hit rate of operations including GeCollectionID, GetCollectionInfo, and GetCollectionSchema per second within the past two minutes.\nThe statistics of hit and failure rate of each cache reading operation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
   "targets": [
    {
     "expr": "sum(increase(milvus_proxy_cache_hit_count{cache_state=\"hit\"}[2m])/120) by(cache_name, node_id) / sum(increase(milvus_proxy_cache_hit_count{}[2m])/120) by(cache_name, node_id)"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "timeseries",
   "description": "The average, maximum, and minimum number of epoch time synced by each proxy in its corresponding physical channel.\nEach physical channel's epoch time (Unix time, the milliseconds passed ever since January 1, 1970).\nThere is a default ChannelName apart from the physical channels.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "expr": "avg(milvus_proxy_sync_epoch_time{}) by (node_id)",
     "legendFormat": "avg_node[{{node_id}}]"
    },
    {
     "expr": " max(milvus_proxy_sync_epoch_time{}) by (node_id)",
     "legendFormat": "max_node[{{node_id}}]"
    },
    {
     "expr": " min(milvus_proxy_sync_epoch_time{}) by (node_id)",
     "legendFormat": "min_node[{{node_id}}]"
    }
   ]
  }
 ]
}