"""Project structure management for GraphRAG-KG.

Handles project initialization, directory creation, docker-compose
generation, and project manifest management.
"""

from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from graphrag_kg.core.config import KGConfig, Neo4jConfig
from graphrag_kg.core.errors import ProjectError

# Default directory structure for a new project
PROJECT_DIRS = [
    "input",
    "output",
    "cache",
    "logs",
    "prompts",
    "documents",
    "config",
]

# Docker Compose template for Neo4j
DOCKER_COMPOSE_TEMPLATE = """\
# GraphRAG-KG Neo4j Service
# Generated by graphrag-kg init on {timestamp}

version: '3.8'

services:
  neo4j:
    image: neo4j:5.22.0
    container_name: graphrag-kg-neo4j
    ports:
      - "{bolt_port}:7687"   # Bolt
      - "{http_port}:7474"   # HTTP
    environment:
      - NEO4J_AUTH={username}/{password}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=1g
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 1;' | cypher-shell -u {username} -p {password} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  milvus:
    image: milvusdb/milvus:latest
    container_name: graphrag-kg-milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - TZ=UTC
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 19530 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s
    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
"""

# Default .env template
ENV_TEMPLATE = """\
# === LLM Configuration ===
GRAPHRAG_API_KEY={api_key}
GRAPHRAG_CHAT_MODEL={chat_model}
GRAPHRAG_EMBEDDING_MODEL={embedding_model}
GRAPHRAG_API_BASE={api_base}

# === Neo4j Configuration ===
NEO4J_URI={neo4j_uri}
NEO4J_USERNAME={neo4j_username}
NEO4J_PASSWORD={neo4j_password}
NEO4J_DATABASE={neo4j_database}
"""

# Default settings.yaml template
SETTINGS_TEMPLATE = """\
# GraphRAG-KG Settings
# Generated by graphrag-kg init on {timestamp}

kg:
  project_name: "{project_name}"
  description: "{description}"

  # Document ingestion settings
  ingestion:
    source_directories:
      - "./documents"
    file_patterns:
      - "**/*.pdf"
      - "**/*.md"
      - "**/*.txt"
      - "**/*.html"
    recursive: true
    encoding: "utf-8"
    clean_html: true
    extract_metadata: true
    max_file_size_mb: 50

  # Pipeline orchestration
  pipeline:
    auto_index_on_ingest: false
    incremental: false
    backup_previous_output: true
    max_workers: 4

  # Query engine settings
  query:
    default_method: "local"
    response_type: "Multiple Paragraphs"
    max_context_tokens: 12000
    include_sources: true
    streaming: false
    cache_ttl_seconds: 3600

  # Neo4j connection
  neo4j:
    uri: "${{NEO4J_URI:bolt://localhost:7687}}"
    username: "${{NEO4J_USERNAME:neo4j}}"
    password: "${{NEO4J_PASSWORD:password}}"
    database: "${{NEO4J_DATABASE:neo4j}}"
    sync_batch_size: 1000
    sync_create_indexes: true
    store_embeddings: false

  # LLM Configuration
  chat_model: "{chat_model}"
  chat_model_provider: "{chat_model_provider}"
  embedding_model: "{embedding_model}"
  embedding_model_provider: "{embedding_model_provider}"
  api_key: "${{GRAPHRAG_API_KEY}}"
  api_base: "${{GRAPHRAG_API_BASE:}}"

# === Standard GraphRAG Settings ===
models:
  default_chat_model:
    type: litellm
    model_provider: {chat_model_provider}
    model: {chat_model}
    api_key: "${{GRAPHRAG_API_KEY}}"
    api_base: "${{GRAPHRAG_API_BASE:}}"

  default_embedding_model:
    type: litellm
    model_provider: {embedding_model_provider}
    model: {embedding_model}
    api_key: "${{GRAPHRAG_API_KEY}}"
    api_base: "${{GRAPHRAG_API_BASE:}}"

input:
  storage:
    type: file
    base_dir: "input"
  type: text
  encoding: "utf-8"
  file_pattern: ".*\\\\.txt$"

chunking:
  type: tokens
  encoding_model: cl100k_base
  size: 1200
  overlap: 100

output:
  type: file
  base_dir: "output"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

reporting:
  type: file
  base_dir: "logs"

vector_store:
  type: milvus
  host: "${{MILVUS_HOST:localhost}}"
  port: ${{MILVUS_PORT:19530}}
  collection_name: "graphrag_vectors"
  metric_type: "COSINE"
  index_params:
    index_type: "IVF_FLAT"
    params:
      nlist: 1024

extract_graph:
  model_id: default_chat_model
  prompt: "prompts/extract_graph.txt"
  entity_types:
    - organization
    - person
    - location
    - event
    - concept
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000

embed_text:
  model_id: default_embedding_model

cluster_graph:
  max_cluster_size: 10

snapshots:
  graphml: true

local_search:
  prompt: "prompts/local_search.txt"

global_search:
  map_prompt: "prompts/global_search_map.txt"
  reduce_prompt: "prompts/global_search_reduce.txt"

drift_search:
  prompt: "prompts/drift_search.txt"
  reduce_prompt: "prompts/drift_reduce.txt"

basic_search:
  prompt: "prompts/basic_search.txt"
"""


class ProjectManager:
    """Manages GraphRAG-KG project lifecycle.

    Handles:
    - Project initialization (directory structure, config files)
    - Docker Compose generation for Neo4j
    - Project manifest (project.json) management
    - Project validation
    """

    def __init__(self, root_dir: Path):
        self.root_dir = Path(root_dir).resolve()

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def init(
        self,
        project_name: str = "my-knowledge-graph",
        description: str = "",
        force: bool = False,
    ) -> KGConfig:
        """Initialize a new GraphRAG-KG project.

        Creates directory structure, settings.yaml, .env, docker-compose.yml,
        and a project manifest.

        Args:
            project_name: Name for the project.
            description: Optional project description.
            force: Overwrite existing files if True.

        Returns:
            The KGConfig for the initialized project.

        Raises:
            ProjectError: If project already exists and force=False.
        """
        # Check if project already exists
        manifest_path = self.root_dir / "project.json"
        if manifest_path.exists() and not force:
            raise ProjectError(
                f"Project already exists at {self.root_dir}. "
                f"Use --force to overwrite."
            )

        # Create directory structure
        for dir_name in PROJECT_DIRS:
            dir_path = self.root_dir / dir_name
            dir_path.mkdir(parents=True, exist_ok=True)

        # Also create neo4j import directory
        (self.root_dir / "neo4j" / "import").mkdir(parents=True, exist_ok=True)

        # Generate config
        config = KGConfig(
            project_name=project_name,
            description=description,
            root_dir=self.root_dir,
        )

        # Write settings.yaml
        self._write_settings(config)

        # Write .env
        self._write_env(config)

        # Write docker-compose.yml
        self._write_docker_compose(config.neo4j)

        # Write project manifest
        self._write_manifest(config)

        return config

    def _write_settings(self, config: KGConfig) -> None:
        """Write settings.yaml to the project root."""
        content = SETTINGS_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).isoformat(),
            project_name=config.project_name,
            description=config.description,
            chat_model=config.chat_model,
            chat_model_provider=config.chat_model_provider,
            embedding_model=config.embedding_model,
            embedding_model_provider=config.embedding_model_provider,
        )
        path = self.root_dir / "settings.yaml"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_env(self, config: KGConfig) -> None:
        """Write .env file to the project root."""
        content = ENV_TEMPLATE.format(
            api_key="${GRAPHRAG_API_KEY}",
            chat_model=config.chat_model,
            embedding_model=config.embedding_model,
            api_base="",
            neo4j_uri=config.neo4j.uri,
            neo4j_username=config.neo4j.username,
            neo4j_password=config.neo4j.password,
            neo4j_database=config.neo4j.database,
        )
        path = self.root_dir / ".env"
        # Don't overwrite existing .env
        if not path.exists():
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)

    def _write_docker_compose(self, neo4j: Neo4jConfig) -> None:
        """Write docker-compose.yml with Neo4j service."""
        # Extract port from URI
        uri = neo4j.uri
        bolt_port = "7687"
        if ":" in uri:
            bolt_port = uri.rsplit(":", 1)[-1]

        content = DOCKER_COMPOSE_TEMPLATE.format(
            timestamp=datetime.now(timezone.utc).isoformat(),
            bolt_port=bolt_port,
            http_port="7474",
            username=neo4j.username,
            password=neo4j.password,
        )
        path = self.root_dir / "docker-compose.yml"
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)

    def _write_manifest(self, config: KGConfig) -> None:
        """Write project.json manifest."""
        manifest = {
            "name": config.project_name,
            "description": config.description,
            "version": "0.1.0",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "config": {
                "chat_model": config.chat_model,
                "embedding_model": config.embedding_model,
            },
        }
        path = self.root_dir / "project.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)

    # ------------------------------------------------------------------
    # Status and validation
    # ------------------------------------------------------------------

    def get_status(self) -> dict:
        """Get project status information."""
        manifest_path = self.root_dir / "project.json"

        status: dict = {
            "initialized": manifest_path.exists(),
            "root_dir": str(self.root_dir),
        }

        if not manifest_path.exists():
            return status

        with open(manifest_path, "r", encoding="utf-8") as f:
            manifest = json.load(f)

        status.update({
            "name": manifest.get("name", "unknown"),
            "description": manifest.get("description", ""),
            "created_at": manifest.get("created_at", ""),
            "updated_at": manifest.get("updated_at", ""),
        })

        # Check index status
        output_dir = self.root_dir / "output"
        if output_dir.exists():
            parquet_files = list(output_dir.glob("*.parquet"))
            status["index_built"] = len(parquet_files) > 0
            status["parquet_files"] = len(parquet_files)

            # Count entities from parquet if available
            if status["index_built"]:
                try:
                    import pandas as pd
                    entities_path = output_dir / "entities.parquet"
                    if entities_path.exists():
                        df = pd.read_parquet(entities_path)
                        status["entity_count"] = len(df)
                    relationships_path = output_dir / "relationships.parquet"
                    if relationships_path.exists():
                        df = pd.read_parquet(relationships_path)
                        status["relationship_count"] = len(df)
                    communities_path = output_dir / "communities.parquet"
                    if communities_path.exists():
                        df = pd.read_parquet(communities_path)
                        status["community_count"] = len(df)
                except Exception:
                    pass
        else:
            status["index_built"] = False

        # Check documents
        input_dir = self.root_dir / "input"
        if input_dir.exists():
            txt_files = list(input_dir.glob("*.txt"))
            status["documents_ingested"] = len(txt_files)

        return status

    def validate(self) -> list[str]:
        """Validate project structure and return list of issues."""
        issues: list[str] = []

        # Check essential directories
        for dir_name in PROJECT_DIRS:
            dir_path = self.root_dir / dir_name
            if not dir_path.exists():
                issues.append(f"Missing directory: {dir_name}")

        # Check settings file
        settings_path = self.root_dir / "settings.yaml"
        if not settings_path.exists():
            issues.append("Missing settings.yaml")

        # Check docker-compose
        compose_path = self.root_dir / "docker-compose.yml"
        if not compose_path.exists():
            issues.append("Missing docker-compose.yml (Neo4j not configured)")

        # Check manifest
        manifest_path = self.root_dir / "project.json"
        if not manifest_path.exists():
            issues.append("Missing project.json (project not initialized)")

        return issues

    @staticmethod
    def is_initialized(root_dir: Path) -> bool:
        """Check if a directory contains an initialized GraphRAG-KG project."""
        manifest_path = Path(root_dir) / "project.json"
        settings_path = Path(root_dir) / "settings.yaml"
        return manifest_path.exists() or settings_path.exists()
