"""Tests for the ProjectManager."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from graphrag_kg.core.project import ProjectManager
from graphrag_kg.core.errors import ProjectError


class TestProjectInit:
    """Project initialization tests."""

    def test_init_creates_structure(self, temp_dir):
        """init() should create the full project directory structure."""
        pm = ProjectManager(temp_dir)
        config = pm.init(project_name="test-project")

        # Check directories
        for dir_name in ["input", "output", "cache", "logs", "prompts", "documents"]:
            assert (temp_dir / dir_name).is_dir(), f"Missing dir: {dir_name}"

        # Check files
        assert (temp_dir / "settings.yaml").exists()
        assert (temp_dir / "docker-compose.yml").exists()
        assert (temp_dir / "project.json").exists()

        # Check config
        assert config.project_name == "test-project"

    def test_init_with_description(self, temp_dir):
        pm = ProjectManager(temp_dir)
        config = pm.init(
            project_name="my-project",
            description="A test knowledge graph",
        )
        assert config.project_name == "my-project"
        assert config.description == "A test knowledge graph"

    def test_init_creates_manifest(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="manifest-test")

        with open(temp_dir / "project.json", "r") as f:
            manifest = json.load(f)

        assert manifest["name"] == "manifest-test"
        assert "created_at" in manifest
        assert "config" in manifest
        assert manifest["config"]["chat_model"] == "gpt-4.1"

    def test_init_creates_settings_yaml(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="settings-test")

        content = (temp_dir / "settings.yaml").read_text(encoding="utf-8")
        assert "settings-test" in content
        assert "neo4j" in content
        assert "vector_store" in content

    def test_init_creates_docker_compose(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="docker-test")

        content = (temp_dir / "docker-compose.yml").read_text(encoding="utf-8")
        assert "neo4j:5.22.0" in content
        assert "7687:7687" in content

    def test_init_refuses_overwrite(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="first")

        with pytest.raises(ProjectError, match="already exists"):
            pm.init(project_name="second")

    def test_init_force_overwrite(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="first")

        # Should not raise with force=True
        config = pm.init(project_name="second", force=True)
        assert config.project_name == "second"

    def test_init_does_not_overwrite_env(self, temp_dir):
        """Existing .env should not be overwritten."""
        (temp_dir / ".env").write_text("CUSTOM_VAR=value")

        pm = ProjectManager(temp_dir)
        pm.init(project_name="env-test", force=True)

        content = (temp_dir / ".env").read_text()
        assert "CUSTOM_VAR=value" in content


class TestProjectStatus:
    """Project status and validation tests."""

    def test_status_uninitialized(self, temp_dir):
        pm = ProjectManager(temp_dir)
        status = pm.get_status()
        assert status["initialized"] is False

    def test_status_initialized(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="status-test")

        status = pm.get_status()
        assert status["initialized"] is True
        assert status["name"] == "status-test"
        assert status["index_built"] is False

    def test_is_initialized(self, temp_dir):
        assert ProjectManager.is_initialized(temp_dir) is False
        pm = ProjectManager(temp_dir)
        pm.init(project_name="check-test")
        assert ProjectManager.is_initialized(temp_dir) is True

    def test_validate_new_project(self, temp_dir):
        pm = ProjectManager(temp_dir)
        pm.init(project_name="validate-test")

        issues = pm.validate()
        assert len(issues) == 0

    def test_validate_empty_dir(self, temp_dir):
        pm = ProjectManager(temp_dir)
        issues = pm.validate()
        assert len(issues) > 0


class TestProjectIntegration:
    """Integration tests with config loading."""

    def test_init_then_load_config(self, temp_dir):
        """Config generated by init should be loadable by ConfigLoader."""
        from graphrag_kg.core.config_loader import ConfigLoader

        pm = ProjectManager(temp_dir)
        pm.init(project_name="integration-test")

        loader = ConfigLoader()
        config = loader.load(temp_dir / "settings.yaml")

        assert config.project_name == "integration-test"
        assert config.neo4j.uri == "bolt://localhost:7687"
        assert isinstance(config.graphrag_settings, dict)
